esphome:
  name: m5_core_s3_media_player
  min_version: 2023.12.7
  platformio_options:
    board_build.flash_mode: dio
    board_upload.maximum_size: 16777216
  
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      # need to set a s3 compatible board for the adf-sdk to compile
      # board specific code is not used though
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB:      "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B:  "y"

      #CONFIG_LOG_DEFAULT_LEVEL_DEBUG: "y"
      #CONFIG_LOG_DEFAULT_LEVEL: "4"

psram:
  mode: quad
  speed: 80MHz


external_components:
  - source:
      type: local
      path: /Users/siekmann/Privat/Projects/espHome/M5Stack_Core_S3/esphome/components
    components: [ esp32_m5stack_core_s3, aw9523 ]


# Enable logging
logger:
  deassert_rts_dtr: true
  level: VERBOSE

packages:
  wifi: !include common/wifi.yaml

api:

i2c:
  - id: bus_a
    sda: GPIO12
    scl: GPIO11
    scan: True

aw9523:
  id: aw9523_1
  address: 0x58

esp32_m5stack_core_s3:

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO37

image:
  - file: mdi:volume-minus
    id: volume_minus
    resize: 80x80
  - file: mdi:volume-plus
    id: volume_plus
    resize: 80x80
  - file: mdi:play
    id: play
    resize: 100x100

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 36


display:
  - platform: ili9xxx 
    model: M5Stack 
    dimensions: 320x240
    cs_pin: GPIO3
    dc_pin: GPIO35
    id: m5cores3_lcd
    reset_pin:
      aw9523: aw9523_1
      port: 1
      pin: 1
      mode:
        output: true
    
    lambda: |-
      auto white = Color(255,255,255);
      it.image(100, 60, id(play));
      it.image(0, 162, id(volume_minus));
      it.printf(150, 180, id(roboto), white, "%d", 50);
      it.image(240, 162, id(volume_plus));

touchscreen:
  - platform: ft63x6
    i2c_id: bus_a
    #on_touch:
    #  - logger.log:
    #      format: Touch at (%d, %d)
    #      args: [touch.x, touch.y]


binary_sensor:
  - platform: touchscreen
    name: Volume Minus
    x_min: 0
    x_max: 80
    y_min: 162
    y_max: 242
    on_press:
      then:
        - logger.log: "Volume Minus pressed"

  - platform: touchscreen
    name: Volume Plus
    x_min: 240
    x_max: 320
    y_min: 162
    y_max: 242
    on_press:
      then:
        - logger.log: "Volume Plus pressed"
